CREATE DATABASE IF NOT EXISTS Escola;
USE Escola;

CREATE TABLE IF NOT EXISTS Notas1tri(
	Id INTEGER PRIMARY KEY AUTO_INCREMENT,
	R1 FLOAT DEFAULT -1,
	R2 FLOAT DEFAULT -1,
	R3 FLOAT DEFAULT -1,
	R4 FLOAT DEFAULT -1,
	Participacao FLOAT DEFAULT -1,
	Prova FLOAT DEFAULT -1,
	Rec FLOAT DEFAULT -1
	);

CREATE TABLE IF NOT EXISTS Notas2tri(
	Id INTEGER PRIMARY KEY AUTO_INCREMENT,
	R1 FLOAT DEFAULT -2,
	R2 FLOAT DEFAULT -2,
	R3 FLOAT DEFAULT -2,
	R4 FLOAT DEFAULT -2,
	Participacao FLOAT DEFAULT -2,
	Prova FLOAT DEFAULT -2,
	Rec FLOAT DEFAULT -2
	);
	
CREATE TABLE IF NOT EXISTS Notas3tri(
	Id INTEGER PRIMARY KEY AUTO_INCREMENT,
	R1 FLOAT DEFAULT -3,
	R2 FLOAT DEFAULT -3,
	R3 FLOAT DEFAULT -3,
	R4 FLOAT DEFAULT -3,
	Participacao FLOAT DEFAULT -3,
	Prova FLOAT DEFAULT -3,
	Rec FLOAT DEFAULT -3
	);
	
CREATE TABLE IF NOT EXISTS Aluno(
	Id INTEGER PRIMARY KEY AUTO_INCREMENT,
	Nome VARCHAR(45) NULL,
	Sobrenome VARCHAR(45) NULL,
	Turma VARCHAR(1) NULL,
	Serie TINYINT(1) NULL,
	Numero TINYINT(3) NULL,
	Media1 FLOAT DEFAULT 0,
	Media2 FLOAT DEFAULT 0,
	Media3 FLOAT DEFAULT 0,
	MediaF FLOAT DEFAULT 0
	);
    
ALTER TABLE Notas1tri ADD COLUMN Qtd INT DEFAULT 0;
ALTER TABLE Notas2tri ADD COLUMN Qtd INT DEFAULT 0;
ALTER TABLE Notas3tri ADD COLUMN Qtd INT DEFAULT 0;