-- MySQL Script generated by MySQL Workbench
-- sáb 25 abr 2020 20:06:17 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Notas1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notas1` (
  `Id` TINYINT(6) NOT NULL,
  `R1` FLOAT NULL,
  `R2` FLOAT NULL,
  `R3` FLOAT NULL,
  `R4` FLOAT NULL,
  `Participacao` FLOAT NULL,
  `Prova` FLOAT NULL,
  `Rec` FLOAT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notas2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notas2` (
  `Id` TINYINT(6) NOT NULL,
  `R1` FLOAT NULL,
  `R2` FLOAT NULL,
  `R3` FLOAT NULL,
  `R4` FLOAT NULL,
  `Participacao` FLOAT NULL,
  `Prova` FLOAT NULL,
  `Rec` FLOAT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notas3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notas3` (
  `Id` TINYINT(6) NOT NULL,
  `R1` FLOAT NULL,
  `R2` FLOAT NULL,
  `R3` FLOAT NULL,
  `R4` FLOAT NULL,
  `Participacao` FLOAT NULL,
  `Prova` FLOAT NULL,
  `Rec` FLOAT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `Id` TINYINT(6) NULL,
  `Nome` VARCHAR(45) NULL,
  `Turma` VARCHAR(1) NULL,
  `Serie` TINYINT(1) NULL,
  `Numero` TINYINT(3) NULL,
  `Media1` FLOAT NULL,
  `Media2` FLOAT NULL,
  `Media3` FLOAT NULL,
  `MediaF` FLOAT NULL,
  CONSTRAINT `fk_Aluno_1`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Notas1` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_2`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Notas2` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_3`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Notas3` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
